# Generated by Django 4.2.7 on 2023-11-11 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_doc_image_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('8:00am to 9:00am', '8:00am to 9:00am'), ('9:00am to 10:00am', '9:00am to 10:00am'), ('10:00am to 11:00am', '10:00am to 11:00am'), ('11:00am to 12:00pm', '11:00am to 12:00pm'), ('12:00pm to 1:00pm', '12:00pm to 1:00pm')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_slot',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.availabletime'),
            preserve_default=False,
        ),
    ]
