# Generated by Django 4.2.7 on 2023-11-11 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_availabletime_booking_booked_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='time2',
            field=models.CharField(choices=[('1', '8:00am to 9:00am'), ('2', '9:00am to 10:00am'), ('3', '10:00am to 11:00am'), ('4', '11:00am to 12:00pm'), ('5', '12:00pm to 1:00pm')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
